config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'about', to: 'welcome#about', as: 'about'

  resources :users
  resources :sessions
  resources :events do
    resources :lists
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  validates :name, length: { minimum: 3 }, presence: true
  validates :date, presence: true
  validates :user, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  belongs_to :user
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_uniqueness_of   :email, :name
  validates_presence_of    :email, :name

  validates :password, length: { minimum: 6 }, allow_blank: false
  validates :password, presence: true, on: :create

  has_many :events

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private 


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user


  #TODO change authorized check on current user = nil to current user is not owner of the event
  #HOWTO: add to controllers as       before_filter :authorize, only: [:edit, :update]
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to event_path(@event), notice: "Awesomesauce. You have created an event!"
    else
      render "new", notice: "Bummer! Something went wrong. Please try to save your event again."
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private 

  def event_params
    params.require(:event).permit(:name, :date, :description)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
  end

  def create
    #TO DO How to get lists connected to an event
    @event = Event.find(params[:event_id])
    @list = current_user.lists.build(list_params)
    @list.event = @event

    if @list.save
      redirect_to event_path(@event), notice: "Awesomesauce. You have created a list!"
    else
      render "new", notice: "Bummer! Something went wrong. Please try to save your list again."
    end
  end

  

  private 

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else 
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You have logged out of WhoBringsWhat."
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end



  private 

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/new.html.slim
h2 Create your own WhoBringsWhat event

#form-styling
  = form_for @event do |f|
    .large-3.columns
      = f.label :name, "Event name"
    .large-9.columns
      = f.text_field :name, autofocus: true, placeholder: "e.g. 'Cookie Fest 2014'"

    .large-3.columns
      = f.label :date, "Date & time"
    .large-9.columns
      .auto
        = raw(f.datetime_select(:date, :date_separator => '', :datetime_separator => ' at ' , start_year: Time.now.year, end_year: Time.now.year + 5, minute_step: 5, :order => [:day, :month, :year, :hour, :minute]).gsub('<select', '<select class=""').to_s)

    .large-3.columns
      = f.label :description
    .large-9.columns
      = f.text_area :description, placeholder: "Give your event a short description..."

      button.button.radius type="submit" Save

app/views/events/show.html.slim
h1 = @event.name

h6 = @event.date

h3 = @event.description

h5 = @event.user.name

br Step 1
br
= link_to "create list", new_event_list_path(@event), class: "button radius"

app/views/layouts/_messages.html.slim
- flash.each do |type, message|
  .alert-box data-alert="true" class=type
    .row
      .small-12.columns
        = message
        = link_to "&times;".html_safe, root_path, class: "close"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = content_for?(:title) ? yield(:title) : "WhoBringsWhat"
    = stylesheet_link_tag "application"
    = csrf_meta_tags
    = javascript_include_tag "application"

  body
    .contain-to-grid
      nav.top-bar data-topbar="true"
        ul.title-area
          li.name
            h1 = link_to "WhoBringsWhat", root_path
          li.toggle-topbar.menu-icon
            = link_to "Menu"

        section.top-bar-section
          ul.right
            li.divider
              - if current_user
                li = link_to "Create an event", new_event_path
                li.divider
                li = link_to "Log out", session_path("current"), method: "delete"
                li.divider

              - else
                li = link_to "Sign me up", signup_path
                li.divider
                li = link_to "Log me in", login_path
                li.divider

    = render 'layouts/messages'

    .row
      .large-12.columns

        = yield

app/views/lists/new.html.slim
h2 Create a list for your WhoBringsWhat event

#form-styling
  = form_for [@event, @list], url: event_list_path do |f|
    .large-3.columns
      = f.label :name, "List name"
    .large-9.columns
      = f.text_field :name, autofocus: true, placeholder: "e.g. Let's get this show on the road"

      button.button.radius type="submit" Save

app/views/users/new.html.slim
h1 Sign up for WhoBringsWhat

= form_for @user do |f|
  
  .large-3.columns
    = f.label :name, "Username"
  .large-9.columns
    = f.text_field :name, autofocus: true, placeholder: "Your Username"

  .large-3.columns
    = f.label :email
  .large-9.columns
    = f.email_field :email, placeholder: "email@example.com"

  .large-3.columns
    = f.label :password
  .large-9.columns
    = f.password_field :password

    button.button.radius type="submit" Save

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>